import "./globals.css";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next apps',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  )
}
